// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD_a8GsGqv8OB8Kf1EmZiTSoLi9VnK4F8M',
    appId: '1:1083085269625:web:b4cea5c3fb8db6a47942a8',
    messagingSenderId: '1083085269625',
    projectId: 'fitnesstracker-aca70',
    authDomain: 'fitnesstracker-aca70.firebaseapp.com',
    storageBucket: 'fitnesstracker-aca70.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAXeooGPlxi6QuFtwOIgufj13cX6kR6MM0',
    appId: '1:1083085269625:android:2bcb316525cfb72d7942a8',
    messagingSenderId: '1083085269625',
    projectId: 'fitnesstracker-aca70',
    storageBucket: 'fitnesstracker-aca70.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAgJCDNJhnCoqH4rp_Y2EgYHRW6KVSmJbs',
    appId: '1:1083085269625:ios:5f27b852dd4bea207942a8',
    messagingSenderId: '1083085269625',
    projectId: 'fitnesstracker-aca70',
    storageBucket: 'fitnesstracker-aca70.firebasestorage.app',
    androidClientId: '1083085269625-fsep4lakrn3cc0amtako72k00l4mqs1g.apps.googleusercontent.com',
    iosClientId: '1083085269625-f2g8sc09ugr19ksvvfrprcgv75ea2897.apps.googleusercontent.com',
    iosBundleId: 'com.example.fitnesstracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAgJCDNJhnCoqH4rp_Y2EgYHRW6KVSmJbs',
    appId: '1:1083085269625:ios:5f27b852dd4bea207942a8',
    messagingSenderId: '1083085269625',
    projectId: 'fitnesstracker-aca70',
    storageBucket: 'fitnesstracker-aca70.firebasestorage.app',
    androidClientId: '1083085269625-fsep4lakrn3cc0amtako72k00l4mqs1g.apps.googleusercontent.com',
    iosClientId: '1083085269625-f2g8sc09ugr19ksvvfrprcgv75ea2897.apps.googleusercontent.com',
    iosBundleId: 'com.example.fitnesstracker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD_a8GsGqv8OB8Kf1EmZiTSoLi9VnK4F8M',
    appId: '1:1083085269625:web:6dd692b00f0999b57942a8',
    messagingSenderId: '1083085269625',
    projectId: 'fitnesstracker-aca70',
    authDomain: 'fitnesstracker-aca70.firebaseapp.com',
    storageBucket: 'fitnesstracker-aca70.firebasestorage.app',
  );

}